### ISSUE TITLE
vs-code argdown: images in readme

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#116] opened 2019-07-23 14:57 UTC
Images & screencasts are broken in description of the extension:

![grafik](https://user-images.githubusercontent.com/3662782/61722528-bd904c80-ad6a-11e9-8d45-323db678429b.png)

**Comment by christianvoigt** [comment] 2019-07-23 15:09
this is a duplicate of #107 

It was a temporary problem with "raw links" github images that is fixed by now. The next release of the extension should automatically have working images again.

**Closed by christianvoigt** 2019-07-23 15:09 UTC
