### ISSUE TITLE
Error: Expecting token of type --> Dedent

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#131] opened 2019-11-05 09:08 UTC
Hi! The following constellation results in a parser error (line 4):

![grafik](https://user-images.githubusercontent.com/3662782/68193787-0c798f00-ffb4-11e9-8f31-935a68b5cfe3.png)

The error reads:

```
Expecting token of type --> Dedent <-- but found --> '
' <--(argdown)
```

**Comment by christianvoigt** [comment] 2019-11-07 15:14
This has actually nothing to do with the comment. You can remove it and will still get that error.

Instead, this is a duplicate of #132 

Because of #132 the lexer currently does not recognize empty lines at the end and interprets them as several single line breaks instead. This has the consequence that the lexer inserts remaining Dedent tokens *after* the Newline tokens and not before them. This is a violation of the syntax rules, so the parser will throw an error. This will be fixed in the next version.

**Closed by christianvoigt** 2019-11-07 15:14 UTC
Labels: bug
