### ISSUE TITLE
redundant edges in map

### ISSUE THREAD

**Issue by MichaelAMueller** [christianvoigt/argdown#57] opened 2018-06-04 19:05 UTC
There must be at least 3 arguments for the problem to occur. One way to solve it is to take one conclusion as a statement between two arguments. 
```
<!--Two arrows from Test 2 to Test 3:-->
<Test 1>

(1) Prämisse 1
----
(2) [Konklusion 1]

<Test 2>

(1) [Konklusion 1]
----
(2) [Konklusion 2]

<Test 3>

(1) [Konklusion 2]
----
(2) Konklusion 3

<!--One arrow from Test 2 to Test 3:-->
<Test 1>

(1) Prämisse 1
----
(2) [Konklusion 1]

[Konklusion 1]

<Test 2>

(1) [Konklusion 1]
----
(2) [Konklusion 2]

<Test 3>

(1) [Konklusion 2]
----
(2) Konklusion 3
```

**Comment by ggbetz** [comment] 2018-06-05 07:13
In the Online Editor, the error can be reproduced with the viz.js map. However, when using Dagre, the error doesn't arise.

**Comment by christianvoigt** [comment] 2018-10-03 16:17
@ggbetz: I think the error will arise in both cases, but Dagre will draw the arrows in exactly the same way so that only the top one is visible.

If I understand this correctly, the error only occurs if more than one premise-conclusion-structure is assigned to the same argument, right? In the example the same structures are assigned twice. If I delete the second ones, the double arrows disappear.

At the moment, Argdown does not support assigning several pcs's to the same argument (even if they are instances of the same pcs). Each argument in an Argdown document can only be assigned one occurrence of a pcs. Ideally, Argdown should behave reasonably if you assign more than one pcs to an argument. Basically later pcs assignments should simply overwrite earlier ones. But this is currently not the case. Here is a simplified example. You have to choose the "All" statement selection mode to see the result in the Sandbox map: 

```argdown
<A1>

(1) A
(2) B
----
(3) [C]

<A1>

(1) A
(2) B
----
(3) [C]
```

The easiest fix for cases like these would be to simply "lock" an argument's pcs after its first assignment so that later assignments are completely ignored.

**Comment by ggbetz** [comment] 2018-10-04 12:16
@christianvoigt , I think the error doesn't hinge on the assignment of multiple PCSs to one and the same argument.

Here's another case where double arrows are drawn:

```
<Test 1>
   +> <Test 2>

<Test 1>

(1) Premise
----
(2) [Conclusion 2]

<Test 2>

(1) [Conclusion 2]
----
(2) Conclusion
```

**Comment by christianvoigt** [comment] 2018-10-04 12:41
ah, ok. The explanation for this example is simple: the map plugin first creates edges from all relations (given a selection of statements and arguments). After that it creates "implicit" support edges from equivalence classes. Currently there is no check if the second step produces redundant arrows. That is easy to fix.

**Comment by christianvoigt** [comment] 2019-03-11 13:04
here is another case that produces redundant arrows:

```argdown
===
selection:
  statementSelectionMode: not-used-in-argument
===

[A]
  - [B]
  
<a1>

(1) asdsa
(2) asdasdas
-----
(3) [B]
  -> <a2>


<a2>

(1) [A]
(2) asdasd
----
(3) sadsd

```

While this has the same effect it is neither caused by deriving edges from equivalence classes, nor by using duplicate pcs's. Maybe we should have opened three different issues for these cases, but for the moment I will collect all cases of redundant errors here.

**Closed** 2019-03-15 20:36 UTC
Labels: bug
